export const ADD_GROUPS = 'ADD_GROUPS'
export const DELETE_GROUPS = 'DELETE_GROUPS'
export const UPDATE_GROUPS = 'UPDATE_GROUPS'
export const SELECTED_GROUPS = 'SELECTED_GROUPS'

export const ADD_STATUS = 'ADD_STATUS'
export const DELETE_STATUS = 'DELETE_STATUS'
export const UPDATE_STATUS = 'UPDATE_STATUS'

export const UPDATE_NAME = 'UPDATE_NAME'
